apps/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

apps/articles/urls.py
from django.urls import path
from .views import *

app_name = 'article'

urlpatterns = [
    path("<int:pk>/", ArticleDetailView.as_view(),name="article_detail"),
    path("<int:pk>/edit/", ArticleUpdateView.as_view(),name="article_edit"),
    path("<int:pk>/delete/", ArticleDeleteView.as_view(),name="article_delete"), 
    path("", ArticleListView.as_view(), name="article_list"),
    path("new/", ArticleCreateView.as_view(), name="article_new"),
]

apps/pages/urls.py
from django.urls import path
from .views import *

app_name = 'page'

urlpatterns = [
    path("", HomePageView.as_view(), name="home")
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import PasswordChangeView,PasswordChangeDoneView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.pages.urls',namespace='page')),
    path("account/", include("apps.accounts.urls",namespace='account')),
    path("account/", include("django.contrib.auth.urls")),
    path("articles/", include("apps.articles.urls",namespace='article')), 
]

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    LEVEL_USER = [
        ('p','Pro'),
        ('l','Lite'),
    ]

    age = models.PositiveIntegerField(null=True,blank=True)
    level = models.CharField(max_length=1,choices=LEVEL_USER,default='l')

apps/articles/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class Category(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=64)
    body = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL,null=True,related_name='article')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,null=True,related_name='article')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("article:article_detail", kwargs={"pk": self.pk})

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment = models.CharField(max_length=140)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

apps/pages/models.py
from django.db import models

# Create your models here.

apps/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = UserCreationForm.Meta.fields + ("age","level")

class SingUpForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = UserCreationForm.Meta.fields + ("age","email")

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = UserChangeForm.Meta.fields

apps/articles/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ("comment",)

apps/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import SingUpForm

__all__ = [
    'SignUpView'
]

class SignUpView(CreateView):
    form_class = SingUpForm 
    success_url = reverse_lazy('login')
    template_name = "registration/signup.html"

apps/articles/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,DeleteView,UpdateView,CreateView,FormView

from .models import Article,Comment
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CommentForm

__all__ = [
    'ArticleListView',
    'ArticleDetailView',
    'ArticleUpdateView',
    'ArticleDeleteView',
    'ArticleCreateView'
]

class ArticleListView(ListView):
    model = Article
    template_name = "article/article_list.html"
    context_object_name = 'articles'

class ArticleDetailView(DetailView):
    model = Article
    template_name = "article/article_detail.html"
    context_object_name = 'article'

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            Comment.objects.create(comment=cd['comment'],author=request.user,article=self.get_object())

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["form"] = CommentForm()
        context["comments"] = Comment.objects.filter(article=context['article'])
        return context


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ("title","body")
    template_name = "article/article_edit.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.request.user)
        return queryset

class ArticleDeleteView(DeleteView):
    model = Article
    template_name = "article/article_delete.html"
    success_url = reverse_lazy("article:article_list")

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.request.user)
        return queryset

class ArticleCreateView(LoginRequiredMixin,CreateView):
    model = Article
    template_name = "article/article_new.html"
    fields = (
    "title",
    "body",
    "category",
    )

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

apps/pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

__all__ = [
    'HomePageView',
]

class HomePageView(TemplateView):
    template_name = 'home.html'

apps/articles/templates/article/article_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}


{% block title %}
    Delete Article
{% endblock title %}
    


{% block body %}
    <div class="py-8">
        <div class="container mx-auto text-white">
            <form action="" method="post">{% csrf_token %}
                <p>Are you sure you want to delete "{{ article.title }}"?</p>
                <button class="text-white bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg px-5 py-2.5 text-center m-auto" type="submit">Confirm</button>
            </form>
        </div>
    </div>
{% endblock body %}
    

apps/articles/templates/article/article_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load tailwind_filters %}


{% block title %}
    Article
{% endblock title %}
    


{% block body %}
    <div class="py-8">
        <div class="container mx-auto text-white">
            <h1 class="text-9xl text-center mb-8 font-bold text-blue-100 hover:text-blue-200">{{ article.title }}</h1>
            {% if request.user == article.author %}
            <a class="my-8 text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg px-5 py-2.5 text-center m-auto" href="{% url 'article:article_edit' pk=article.pk %}">Edit</a>
            <a class="my-8 text-white bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg px-5 py-2.5 text-center m-auto" href="{% url 'article:article_delete' pk=article.pk %}">Delete</a>
            {% endif %}
            <p class="text-xl">{{ article.body }}</p>
            <small class="italic text-yellow-600 m-5">{{ article.created }}</small>
            <small class="italic text-yellow-600 m-5">{{ article.author }}</small>
        </div>

        <div class="container mx-auto bg-gray-700 text-gray-100 p-8 mt-8">
            
            {% for comment in comments %}
            <div class="border-dashed  border-2 border-sky-500 rounded p-5">
                {{ comment.comment }}
                <small>{{comment.created | timesince}}</small>
            </div>
            {% empty %}
            Not Exist comment
            {% endfor %}

            {% if form %}
                <form method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="submit" class="text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 font-medium rounded-lg px-5 py-2.5 text-center m-auto" value="Send">

                </form>
            {% endif %}
        </div>
    </div>
{% endblock body %}
    

apps/articles/templates/article/article_edit.html
{% extends 'base.html' %}
{% load tailwind_filters %}


{% block title %}
    Edit Article
{% endblock title %}
    


{% block body %}
    <div class="py-8">
        <div class="container mx-auto text-white">
            <form method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" class="text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 font-medium rounded-lg px-5 py-2.5 text-center m-auto" value="Edit">
            </form>
        </div>
    </div>
{% endblock body %}
    

apps/articles/templates/article/article_list.html
{% extends 'base.html' %}


{% block title %}
    Articles
{% endblock title %}
    


{% block body %}
    <div class="text-blue-900 py-8">
        <div class="container mx-auto">
            <div class="bg-white rounded-lg shadow-lg p-6">
                <h1 class="text-2xl font-bold mb-4">Article List</h1>
                <ul class="divide-y divide-gray-200">
                    {% for article in articles %}
                        <hr>
                        <li class="py-4">
                            <a href="{{ article.get_absolute_url }}" class="block hover:underline">
                                <h2 class="text-lg font-bold">{{ article.title }}</h2>
                                <p class="text-gray-700 mt-2">{{ article.body|truncatechars:100 }}</p>
                            </a>
                        </li>
                    {% empty %}
                        <p>No articles found.</p>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock body %}
    

apps/articles/templates/article/article_new.html
{% extends 'base.html' %}
{% load tailwind_filters %}


{% block title %}
    New Article
{% endblock title %}
    


{% block body %}
    <div class="py-8">
        <div class="container mx-auto text-white">
            <form method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" class="text-white bg-gradient-to-r from-green-500 via-green-600 to-green-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-green-300 dark:focus:ring-green-800 font-medium rounded-lg px-5 py-2.5 text-center m-auto" value="Add">
            </form>
        </div>
    </div>
{% endblock body %}
    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CDN tailwind -->
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.css" rel="stylesheet" />


    <title>{% block title %}{% endblock title %}</title>

    {% block head %} {% endblock head %}
</head>
<body class="bg-gray-800">
    <header>
        <nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900">
            <div class="container flex flex-wrap items-center justify-between mx-auto">
            <a href="https://flowbite.com/" class="flex items-center">
                <img src="https://flowbite.com/docs/images/logo.svg" class="h-6 mr-3 sm:h-9" alt="Flowbite Logo" />
                <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
            </a>
            <div class="flex md:order-2">
              <button type="button" data-collapse-toggle="navbar-search" aria-controls="navbar-search" aria-expanded="false" class="md:hidden text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5 mr-1" >
                <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
                <span class="sr-only">Search</span>
              </button>
              <div class="relative hidden md:block">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                  <svg class="w-5 h-5 text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
                  <span class="sr-only">Search icon</span>
                </div>
                <input type="text" id="search-navbar" class="block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
              </div>
              <button data-collapse-toggle="navbar-search" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-search" aria-expanded="false">
                <span class="sr-only">Open menu</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
              </button>
            </div>
              <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-search">
                <div class="relative mt-3 md:hidden">
                  <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    <svg class="w-5 h-5 text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
                  </div>
                  <input type="text" id="search-navbar" class="block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
                </div>
                <ul class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                  <li>
                    <a href="{% url 'page:home' %}" class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white" aria-current="page">Home</a>
                    <a href="{% url 'article:article_list' %}" class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white" aria-current="page">Articles</a>
                  </li>
                  {% if request.user.is_authenticated %}
                  <li>
                    <a href="{% url 'article:article_new' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Create Article</a>
                    <a href="{% url 'password_change' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Change Passowrd</a>
                    <a href="{% url 'logout' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Logout</a>
                  </li>
                  {% else %}
                    <li>
                      <a href="{% url 'login' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Login</a>
                    </li>
                    <li>
                      <a href="{% url 'account:signup' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">SignUp</a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
    </header>
    <main class="container mx-auto mt-4 text-blue-50">
      {% block body %} {% endblock body %}
    </main>
<footer></footer>
</body>
</html>

templates/home.html
{% extends 'base.html' %}


{% block title %}Home{% endblock title %}


{% block body %}
<div class="text-center">
    <h1>Test Page</h1>
</div>
{% endblock body %}
    
    